-- MySQL Script generated by MySQL Workbench
-- 03/17/16 14:52:22
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sample_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `samples`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samples` ;

CREATE TABLE IF NOT EXISTS `samples` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(128) NOT NULL COMMENT '名前',
  `age` INT(3) NOT NULL COMMENT '年齢',
  `birthday` DATE NOT NULL COMMENT '誕生日',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `modified` DATETIME NOT NULL COMMENT '更新日時',
  `delete_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ（false..有効、true..削除）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'サンプル';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
